s = set()
n = input("enter number 1: ")
s.add(int(n))
n = input("enter number 2: ")
s.add(int(n))
n = input("enter number 3: ")
s.add(int(n))
n = input("enter number 4: ")
s.add(int(n))
n = input("enter number 5: ")
s.add(int(n))
n = input("enter number 6: ")
s.add(int(n))
n = input("enter number 7: ")
s.add(int(n))

